'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {Activity,ArrowLeft,CheckCircle2,RefreshCw,TriangleAlert} from 'lucide-react';
import styles from './operations.module.css';
type Issue={id:string;source:string;code:string;stage:string;version:string;errorType:string;location:string;firstSeen:number;lastSeen:number;count:number;state:string;regressions:number;clients:number};
export type Snapshot={asOf:number;issues:Issue[];probes:{id:string;status:number;checked:number;failures:number;latency:number}[]};
const time=(value:number)=>new Date(value).toISOString().replace('T',' ').slice(0,19)+' UTC';
const names:Record<string,string>={api:'Family services & database',parent:'Parent dashboard',updates:'Child update feed'};
const label=(issue:Issue)=>issue.source==='health'?`${names[issue.stage]||issue.stage} unavailable`:issue.code==='55P03'?'Database operation waited too long':issue.code==='slow_request'?'Slow response':issue.stage.startsWith('installer-')?'Child installer needs investigation':`${issue.stage.replaceAll('-',' ')} · ${issue.code.replaceAll('_',' ')}`;
async function request(action:string,input:Record<string,unknown>={}){const response=await fetch('/guard/admin/bridge/',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...input})});const data=await response.json();if(!response.ok)throw Error(data.error||'Monitoring could not be reached.');return data;}
export default function OperationsPanel({initial}:{initial:Snapshot|null}){
 const [snapshot,setSnapshot]=useState(initial),[error,setError]=useState(initial?'':'Monitoring could not be reached. The last status is unknown.'),[busy,setBusy]=useState(false),[filter,setFilter]=useState('active'),[clock,setClock]=useState(initial?.asOf||0);
 const refresh=useCallback(async()=>{setBusy(true);try{setSnapshot(await request('operations'));setError('');}catch(error){setError(error instanceof Error?error.message:'Monitoring could not be reached.');}finally{setBusy(false);setClock(Date.now());}},[]);
 useEffect(()=>{const timer=setInterval(()=>{setClock(Date.now());if(document.visibilityState==='visible')void refresh();},60000);const resume=()=>{if(document.visibilityState==='visible')void refresh();};document.addEventListener('visibilitychange',resume);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',resume);};},[refresh]);
 async function change(issue:Issue,state:string){setBusy(true);try{const result=await request('operation-state',{id:issue.id,state,lastSeen:issue.lastSeen});if(!result.updated)throw Error('This incident changed. Refresh and review the latest report.');await refresh();}catch(error){setError(error instanceof Error?error.message:'Could not save this change.');}finally{setBusy(false);}}
 const active=snapshot?.issues.filter(issue=>issue.state!=='resolved')||[],visible=snapshot?.issues.filter(issue=>filter==='all'||(filter==='resolved'?issue.state==='resolved':issue.state!=='resolved'))||[];
 return <div className={styles.surface}><main className={styles.page}>
  <header className={styles.header}><div><span className={styles.eyebrow}><Activity size={17}/> BODEEGUARD STAFF</span><h1>Service health</h1><p>Cloud checks and application incidents. Alerts stay here; no emails are sent.</p></div><Link href='/guard/admin/'><ArrowLeft size={17}/> Staff dashboard</Link></header>
  <div className={styles.toolbar}><div><strong>{active.length} active incident{active.length===1?'':'s'}</strong><span>{snapshot?`Updated ${time(snapshot.asOf)}`:'Waiting for monitoring'}</span></div><button disabled={busy} onClick={()=>void refresh()}><RefreshCw size={17}/> {busy?'Checking…':'Refresh'}</button></div>
  {(error||snapshot&&clock-snapshot.asOf>120000)&&<p role='alert' className={styles.warning}>{error||'This view is out of date. Refresh to check current health.'}</p>}
  <section className={styles.probes} aria-label='Automatic service checks'>{Object.entries(names).map(([id,name])=>{const probe=snapshot?.probes.find(p=>p.id===id),stale=!probe||clock-probe.checked>12*60000,healthy=!stale&&probe.status===200;return <article key={id} data-state={stale?'unknown':healthy?'healthy':'failed'}>{healthy?<CheckCircle2 size={24}/>:<TriangleAlert size={24}/>}<div><h2>{name}</h2><strong>{stale?'Status unknown':healthy?'Available':probe.failures<2?'Rechecking failure':'Needs attention'}</strong><small>{probe?`Checked ${time(probe.checked)} · ${probe.latency} ms`:'First check has not arrived'}</small></div></article>;})}</section>
  <p className={styles.help}>Checks run every 5 minutes, even when this page is closed. Two failed checks open an incident; recovery closes it automatically.</p>
  <div className={styles.toolbar}><h2>Incidents</h2><label>Show <select value={filter} onChange={event=>setFilter(event.target.value)}><option value='active'>Open & investigating</option><option value='resolved'>Resolved</option><option value='all'>All</option></select></label></div>
  <section className={styles.incidents}>{visible.map(issue=><article key={issue.id} className={styles.incident} data-state={issue.state}><div className={styles.incidentHead}><div><span className={styles.eyebrow}>{issue.source==='child'||issue.source==='parent'?'Client reported':issue.source==='health'?'Automatic check':'Server detected'}</span><h3>{label(issue)}</h3></div><span className={styles.badge}>{issue.state==='acknowledged'?'Investigating':issue.state}{issue.regressions>0?` · Reopened ${issue.regressions}×`:''}</span></div><div className={styles.facts}><span><strong>{issue.count}</strong> reports</span><span>Latest version <strong>{issue.version}</strong></span><span>Last seen <strong>{time(issue.lastSeen)}</strong></span></div><details><summary>Diagnostic details</summary><dl><dt>Code / stage</dt><dd>{issue.code} / {issue.stage}</dd><dt>Error type</dt><dd>{issue.errorType}</dd><dt>Source location</dt><dd>{issue.location}</dd><dt>First seen</dt><dd>{time(issue.firstSeen)}</dd><dt>Incident</dt><dd>{issue.id.slice(0,12)}</dd></dl></details>{issue.source!=='health'&&issue.state!=='resolved'&&<div className={styles.actions}>{issue.state==='open'&&<button disabled={busy} onClick={()=>void change(issue,'acknowledged')}>Mark investigating</button>}<button disabled={busy} onClick={()=>void change(issue,'resolved')}>Mark resolved</button></div>}</article>)}{!visible.length&&<div className={styles.empty}><CheckCircle2 size={28}/><h3>{snapshot?'No incidents in this view':'Monitoring is unavailable'}</h3><p>{snapshot?'Only received reports are counted. A quiet report list does not prove every child computer is healthy.':'Try refreshing. An unavailable monitor must not be treated as a healthy service.'}</p></div>}</section>
  <p className={styles.help}>Reports are retained for 30 days. Repeated delivery is deduplicated. Later failures reopen resolved incidents. No documents, screenshots, message text, passwords or full addresses are collected. Client reports are unverified diagnostic signals.</p>
 </main></div>;
}
