import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import Module from 'node:module';
import test from 'node:test';
import ts from 'typescript';
function route({signedIn=true,fail=false}={}){const file=path.resolve('app/guard/dashboard/worksheets/route.ts'),module=new Module(file),calls=[];class CloudApiError extends Error{}module.require=name=>{if(name==='@clerk/nextjs/server')return{auth:async()=>({isAuthenticated:signedIn})};if(name==='../cloud-api')return{CloudApiError,cloudApi:async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});if(fail)throw Error('Synthetic private detail');return{saved:true};}};throw Error('Unexpected route dependency');};module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,file);return{POST:module.exports.POST,calls};}
function request(body,headers={}){return new Request('https://guard.bodeebooks.com/guard/dashboard/worksheets/',{method:'POST',headers:{origin:'https://guard.bodeebooks.com','content-type':'application/json',...headers},body:typeof body==='string'?body:JSON.stringify(body)});}
test('Worksheet route requires parent origin and authentication, bounds parts and strips forged storage and family fields',async()=>{const f=route();assert.equal((await f.POST(request({action:'list'},{origin:'https://foreign.example'}))).status,403);assert.equal((await route({signedIn:false}).POST(request({action:'list'}))).status,401);assert.equal((await f.POST(request('x'.repeat(1536001)))).status,413);assert.equal((await f.POST(request({action:'upload',kind:'delete'}))).status,400);await f.POST(request({action:'upload',kind:'put',worksheetId:'page',position:0,data:'Zg==',householdId:'forged',storagePath:'other'}));assert.deepEqual(f.calls[0],{url:'/worksheets/upload',body:{kind:'put',worksheetId:'page',position:0,data:'Zg=='}});await f.POST(request({action:'file',worksheetId:'page',view:'part',position:0,householdId:'forged',url:'foreign'}));assert.deepEqual(f.calls[1],{url:'/worksheets/file',body:{worksheetId:'page',view:'part',position:0}});const failure=await route({fail:true}).POST(request({action:'list'}));assert.equal(failure.status,503);assert.doesNotMatch(JSON.stringify(await failure.json()),/private detail/);});
