"use client";
import {useState,useEffect,useRef,useCallback} from "react";
import Link from "next/link";
import {Activity,ArrowLeft,ArrowUp,ArrowDown,BarChart3,Check,ChevronLeft,ChevronRight,Download,ExternalLink,Eye,FileImage,ImageIcon,Library,LoaderCircle,Monitor,Music,Plus,RefreshCw,Save,Search,ShieldCheck,Trash2,Upload,Users,Video,X,AlertTriangle,Send} from "lucide-react";
import type {Overview,Catalog,Item,Report} from "./types";
import styles from "./admin.module.css";
import UsagePanel from "./UsagePanel";
const groups=[{id:"music",title:"Music",Icon:Music},{id:"videos",title:"Videos",Icon:Video},{id:"artwork",title:"Artwork",Icon:ImageIcon},{id:"worksheets",title:"Worksheets",Icon:FileImage},{id:"learning-videos",title:"Learning videos",Icon:Video}];
const date=(value:string)=>new Date(value).toLocaleString();
async function request<T>(action:string,input:Record<string,unknown>={}):Promise<T>{const response=await fetch("/guard/admin/bridge/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...input})});const result=await response.json();if(!response.ok)throw Error(result.error||"Request failed.");return result;}
function videoId(value:string){if(/^[\w-]{11}$/.test(value))return value;try{const url=new URL(value);if(url.hostname==="youtu.be")return url.pathname.slice(1);return url.searchParams.get("v")||url.pathname.split("/").at(-1)||"";}catch{return "";}}
async function imageUpload(file:File){
  if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>32*1024*1024)throw Error("Choose a PNG, JPG or WebP image up to 32 MB.");
  const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,2400/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d")!.drawImage(bitmap,0,0,canvas.width,canvas.height);
    const data=canvas.toDataURL("image/webp",.9).split(",")[1];if(data.length>2800000)throw Error("This image is still too large. Use a smaller drawing.");return data;
  }finally{bitmap.close();}
}
export default function OperatorPanel({initial,initialTab='overview'}:{initial:Overview;initialTab?:string}){
  const [tab,setTab]=useState(initialTab==='usage'?'usage':'overview'),[overview,setOverview]=useState(initial),[catalog,setCatalog]=useState<Catalog|null>(null),[category,setCategory]=useState("music"),[search,setSearch]=useState(""),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[reports,setReports]=useState<Report[]>([]),[reference,setReference]=useState(""),[preview,setPreview]=useState<{items:Item[];index:number}|null>(null),[image,setImage]=useState(""),[previewError,setPreviewError]=useState("");
  const upload=useRef<HTMLInputElement>(null),cache=useRef(new Map<string,string>()),modal=useRef<HTMLDialogElement>(null);
  const work=useCallback(async(task:()=>Promise<void>)=>{setBusy(true);setError("");setNotice("");try{await task();}catch(error){setError(error instanceof Error?error.message:"Try again.");}finally{setBusy(false);}},[]);
  function navigate(next:string){if(busy)return;setTab(next);const url=new URL(window.location.href);url.searchParams.set('tab',next);window.history.replaceState(null,'',url);if(next==="content"&&!catalog)void work(async()=>setCatalog(await request<Catalog>("catalog")));if(next==="reports")void work(async()=>setReports((await request<{reports:Report[]}>("reports")).reports));}
  useEffect(()=>{if(initialTab==='content'){setTab('content');void work(async()=>setCatalog(await request<Catalog>('catalog')));}else if(initialTab==='reports'){setTab('reports');void work(async()=>setReports((await request<{reports:Report[]}>('reports')).reports));}},[initialTab,work]);
  const current=preview?.items[preview.index];
  useEffect(()=>{if(!preview)return;modal.current?.showModal();const focus=document.activeElement;return()=>{if(focus instanceof HTMLElement)focus.focus();};},[!!preview]);
  useEffect(()=>{let canceled=false;setImage("");setPreviewError("");if(!current||current.youtubeId)return;
    const cached=cache.current.get(current.id);if(cached){setImage(cached);return;}
    void request<{mime:string;data:string}>("preview",{itemId:current.id,size:"full"}).then(file=>{const src=`data:${file.mime};base64,${file.data}`;cache.current.set(current.id,src);if(!canceled)setImage(src);}).catch(error=>{if(!canceled)setPreviewError(error.message);});return()=>{canceled=true;};
  },[current?.id,current?.youtubeId]);
  useEffect(()=>{if(!dirty)return;const listener=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener("beforeunload",listener);return()=>window.removeEventListener("beforeunload",listener);},[dirty]);
  function change(id:string,patch:Partial<Item>){setCatalog(value=>value&&({...value,items:value.items.map(item=>item.id===id?{...item,...patch}:item)}));setDirty(true);}
  function move(id:string,amount:number){if(!catalog)return;const items=[...catalog.items],index=items.findIndex(item=>item.id===id),siblings=items.map((item,i)=>({item,i})).filter(row=>row.item.category===category),position=siblings.findIndex(row=>row.item.id===id),other=siblings[position+amount]?.i;if(other===undefined)return;[items[index],items[other]]=[items[other],items[index]];setCatalog({...catalog,items});setDirty(true);}
  async function saveDraft(){if(!catalog)throw Error("Load the collection first.");const saved=await request<Catalog>("save",{revision:catalog.revision,items:catalog.items});setCatalog(saved);setDirty(false);return saved;}
  function showPreview(item:Item){const items=catalog!.items.filter(row=>row.category===category);setPreview({items,index:items.findIndex(row=>row.id===item.id)});}
  function step(amount:number){setPreview(value=>value&&({...value,index:Math.max(0,Math.min(value.items.length-1,value.index+amount))}));}
  const selected=groups.find(group=>group.id===category)!,visible=catalog?.items.filter(item=>item.category===category&&`${item.title} ${item.description}`.toLowerCase().includes(search.toLowerCase()))||[];
  return <main className={styles.page}>
    <header className={styles.header}><div><span className={styles.eyebrow}><ShieldCheck size={18}/> BODEEGUARD STAFF</span><h1>Product dashboard</h1><p>Collections, adoption and support in one place.</p></div><Link href="/guard/account/"><ArrowLeft size={17}/> Parent account</Link></header>
    <nav className={styles.tabs} aria-label="Staff sections">{[{id:"overview",label:"Overview",Icon:BarChart3},{id:"usage",label:"Usage & costs",Icon:Activity},{id:"content",label:"Starter content",Icon:Library},{id:"reports",label:"Errors & reports",Icon:AlertTriangle}].map(({id,label,Icon})=><button key={id} aria-current={tab===id?"page":undefined} onClick={()=>navigate(id)}><Icon size={18}/>{label}</button>)}</nav>
    {error&&<p role="alert" className={styles.error}>{error}</p>}{notice&&<p role="status" className={styles.notice}><Check size={17}/>{notice}</p>}
    {tab==="usage"&&<UsagePanel/>}
    {tab==="overview"&&<>
      <div className={styles.sectionHead}><h2>Product health</h2><button disabled={busy} onClick={()=>void work(async()=>setOverview(await request<Overview>("overview")))}><RefreshCw size={16}/> Refresh</button></div>
      <div className={styles.stats}>{[{label:"Families",value:overview.accounts.total,detail:`${overview.accounts.new} new in 30 days`,Icon:Users},{label:"Child computers",value:overview.devices.total,detail:`${overview.devices.online} seen in the last 5 minutes`,Icon:Monitor},{label:"Active families",value:overview.devices.active_families,detail:"Computer connected in the last 7 days",Icon:Activity},{label:"Download starts",value:overview.downloads.requests,detail:`${overview.downloads.families} families · last 30 days`,Icon:Download}].map(({label,value,detail,Icon})=><article key={label}><Icon size={22}/><span>{label}</span><strong>{value.toLocaleString()}</strong><small>{detail}</small></article>)}</div>
      <div className={styles.columns}>
        <section className={styles.panel}><h2><Download size={20}/> Website download starts</h2><p>Account download links issued. These are not completed file transfers. Tracking begins with this panel.</p><div className={styles.chart} aria-label="Daily download starts">{overview.daily.length?overview.daily.map(day=><div key={day.date} title={`${day.date}: ${day.count}`}><span style={{height:Math.max(3,day.count/Math.max(...overview.daily.map(row=>row.count))*110)}}/><small>{day.date.slice(5)}</small></div>):<p>No download requests recorded yet.</p>}</div></section>
        <section className={styles.panel}><h2><Monitor size={20}/> Installed versions</h2><p>Latest reported version for each connected child computer.</p>{overview.versions.map(row=><div className={styles.metricRow} key={row.version}><span>{row.version}</span><strong>{row.computers} computer{row.computers===1?"":"s"}</strong></div>)}{!overview.versions.length&&<p>No computers paired yet.</p>}</section>
        <section className={styles.panel}><h2><Users size={20}/> Setup & activity</h2><div className={styles.metricRow}><span>Family guides completed</span><strong>{overview.onboarding.completed} / {overview.onboarding.started}</strong></div><div className={styles.metricRow}><span>Children studying · 7 days</span><strong>{overview.activity.students}</strong></div><div className={styles.metricRow}><span>Received schoolwork · 7 days</span><strong>{Math.round(Number(overview.activity.seconds)/3600)} hours</strong></div><div className={styles.metricRow}><span>Active accounts / trials</span><strong>{overview.accounts.active} / {overview.accounts.trials}</strong></div><p>{overview.accounts.complimentary} complimentary accounts included.</p></section>
        <section className={styles.panel}><h2><Library size={20}/> Starter approval</h2>{groups.map(group=>{const row=overview.adoption.find(row=>row.category===group.id);return <div className={styles.metricRow} key={group.id}><span>{group.title}</span><strong>{row?.approved||0} approved · {row?.skipped||0} skipped</strong></div>;})}</section>
        <section className={styles.panel}><h2><AlertTriangle size={20}/> Setup reports · 30 days</h2><div className={styles.metricRow}><span>Success reports</span><strong>{overview.outcomes.completed}</strong></div><div className={styles.metricRow}><span>Failure reports</span><strong>{overview.outcomes.failed}</strong></div><p>Client-reported diagnostics; not confirmed installation totals.</p><button onClick={()=>navigate("reports")}><Eye size={16}/> Review errors</button></section>
        {overview.ai&&<section className={styles.panel}><h2><BarChart3 size={20}/> AI costs · this month</h2><div className={styles.metricRow}><span>Estimated provider cost</span><strong>{(Number(overview.ai.totals.cost_micros)/1000000).toLocaleString('en-US',{style:'currency',currency:'USD'})}</strong></div><div className={styles.metricRow}><span>Per family using AI</span><strong>{(Number(overview.ai.totals.cost_micros)/1000000/Math.max(1,overview.ai.totals.families)).toLocaleString('en-US',{style:'currency',currency:'USD'})}</strong></div><p>{overview.ai.totals.requests} provider requests · {overview.ai.totals.families} families. Tracking starts with this update. Estimates use provider tokens where available; voice and unknown outcomes use reserved estimates. Hosting, payment fees and support are separate.</p>{overview.ai.features.map(row=><div className={styles.metricRow} key={row.feature+row.model}><span>{row.feature.replaceAll('-',' ')}<small> · {row.requests} requests</small></span><strong>{(Number(row.cost_micros)/1000000).toLocaleString('en-US',{style:'currency',currency:'USD'})}</strong></div>)}<details><summary>Cost by family</summary>{overview.ai.families.map(row=><div key={row.family} className={styles.metricRow}><span>Family {row.family}<small> · {row.billing_mode} · {row.child_computer_limit} computers</small></span><strong>{(Number(row.cost_micros)/1000000).toLocaleString('en-US',{style:'currency',currency:'USD'})}</strong></div>)}</details><p>Included AI cost budget: $3 per family/month + $0.30 per extra computer. Optional $5 boosts add $3 of provider allowance.</p></section>}
        <section className={styles.panel}><h2><Activity size={20}/> Staff changes</h2>{overview.audit.map((event,index)=><div className={styles.metricRow} key={index}><span>{event.action}{event.version?` · v${event.version}`:""}</span><small>{date(event.created_at)}</small></div>)}{!overview.audit.length&&<p>No staff changes recorded yet.</p>}</section>
      </div><p className={styles.updated}>Updated {date(overview.asOf)}</p>
    </>}
    {tab==="content"&&<>
      <div className={styles.sectionHead}><div><h2>Starter content</h2><p>Parents approve these collections during setup. Published changes apply to new families.</p></div><div className={styles.actions}><button disabled={busy||!catalog||!dirty} onClick={()=>void work(async()=>{await saveDraft();setNotice("Draft saved.");})}><Save size={17}/> Save draft</button><button className={styles.primary} disabled={busy||!catalog} onClick={()=>void work(async()=>{const saved=dirty?await saveDraft():catalog!;const result=await request<Catalog>("publish",{revision:saved.revision});setCatalog(result);setNotice(`Version ${result.publishedVersion} is published for new families.`);})}><Send size={17}/> Publish for new families</button></div></div>
      {catalog?<><p className={styles.updated}>Published v{catalog.publishedVersion} · {dirty?"Unsaved changes":"Draft saved"} · Existing family libraries stay as approved.</p>
      <div className={styles.collectionTabs}>{groups.map(({id,title,Icon})=><button key={id} aria-pressed={category===id} onClick={()=>{setCategory(id);setSearch("");}}><Icon size={17}/>{title}<small>{catalog.items.filter(item=>item.category===id&&item.enabled).length}</small></button>)}</div>
      <div className={styles.toolbar}><label className={styles.search}><Search size={17}/><input aria-label="Find starter content" value={search} onChange={event=>setSearch(event.target.value)} placeholder={`Find ${selected.title.toLowerCase()}…`}/></label>
      {["artwork","worksheets"].includes(category)?<><input ref={upload} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>{const file=event.target.files?.[0];event.target.value="";if(file)void work(async()=>{const data=await imageUpload(file),result=await request<{item:Item}>("upload",{category,title:file.name.replace(/\.[^.]+$/,"").slice(0,120),data});setCatalog(value=>value&&({...value,items:[...value.items,result.item]}));setDirty(true);setNotice("Image uploaded. Save and publish when ready.");});}}/><button disabled={busy} onClick={()=>upload.current?.click()}><Upload size={17}/> Upload {category==="artwork"?"drawing":"worksheet"}</button></>:<button disabled={busy} onClick={()=>{setCatalog({...catalog,items:[...catalog.items,{id:crypto.randomUUID(),category,title:"",description:"",youtubeId:"",enabled:true}]});setDirty(true);setSearch("");}}><Plus size={17}/> Add YouTube link</button>}
      </div>
      <div className={styles.itemList}>{visible.map(item=><article key={item.id} className={styles.item}>
        <label className={styles.itemToggle}><input type="checkbox" checked={item.enabled} disabled={busy} onChange={event=>change(item.id,{enabled:event.target.checked})}/><span>Include</span></label>
        <button className={styles.previewButton} onClick={()=>showPreview(item)} aria-label={`Preview ${item.title||"new item"}`}><Eye size={22}/><span>Preview</span></button>
        <div className={styles.fields}><label>Title<input maxLength={120} value={item.title} disabled={busy} onChange={event=>change(item.id,{title:event.target.value})}/></label>{!["artwork","worksheets"].includes(item.category)&&<label>YouTube link or video ID<input value={item.youtubeId} maxLength={2048} disabled={busy} onChange={event=>change(item.id,{youtubeId:event.target.value})}/></label>}<label>Description<input maxLength={300} value={item.description} disabled={busy} onChange={event=>change(item.id,{description:event.target.value})}/></label></div>
        <div className={styles.itemActions}><button title="Move up" aria-label={`Move ${item.title} up`} disabled={busy} onClick={()=>move(item.id,-1)}><ArrowUp size={17}/></button><button title="Move down" aria-label={`Move ${item.title} down`} disabled={busy} onClick={()=>move(item.id,1)}><ArrowDown size={17}/></button><button title="Remove from draft" aria-label={`Remove ${item.title} from draft`} disabled={busy} onClick={()=>{setCatalog({...catalog,items:catalog.items.filter(row=>row.id!==item.id)});setDirty(true);}}><Trash2 size={17}/></button></div>
      </article>)}</div>{!visible.length&&<p className={styles.empty}>No items here yet.</p>}
      <details className={styles.panel}><summary>Published history</summary>{catalog.history.map(row=><div className={styles.metricRow} key={row.version}><strong>Version {row.version}</strong><span>{date(row.published_at)}</span></div>)}</details>
      </>:<p className={styles.empty}><LoaderCircle size={22}/> Loading collections…</p>}
    </>}
    {tab==="reports"&&<>
      <div className={styles.sectionHead}><div><h2>Errors & reports</h2><p>Latest 100 reports from the last 30 days. No screenshots, messages or passwords.</p></div><button disabled={busy} onClick={()=>void work(async()=>setReports((await request<{reports:Report[]}>("reports",{reference})).reports))}><RefreshCw size={17}/> Refresh</button></div>
      <form className={styles.toolbar} onSubmit={event=>{event.preventDefault();void work(async()=>setReports((await request<{reports:Report[]}>("reports",{reference})).reports));}}><label className={styles.search}><Search size={17}/><input aria-label="Report reference" placeholder="Find BG-… reference" value={reference} maxLength={40} onChange={event=>setReference(event.target.value)}/></label><button disabled={busy}>Find reports</button></form>
      <section className={styles.panel}><h2>Most reported errors</h2>{overview.errors.map((row,index)=><div className={styles.metricRow} key={index}><span>{row.code.replaceAll("_"," ")} · {row.component} · {row.version}</span><strong>{row.count}</strong></div>)}{!overview.errors.length&&<p>No error reports received.</p>}</section>
      <div className={styles.columns}>{reports.map(report=><article className={styles.panel} key={report.id}><span className={styles.eyebrow}>BG-{report.id.replaceAll("-","").slice(0,12)}</span><h2>{report.code.replaceAll("_"," ")}</h2><p>{report.component} · App {report.version} · Windows {report.osVersion}</p><p>Stage: {report.stage}{report.windowsError?` · Windows error ${report.windowsError}`:""}</p>{report.errorType!=="none"&&<p>{report.errorType}</p>}{report.location!=="unknown"&&<code>{report.location}</code>}<small>{date(report.receivedAt)} · Client-reported</small></article>)}</div>{!busy&&!reports.length&&<p className={styles.empty}>No matching reports.</p>}
    </>}
    {preview&&current&&<dialog ref={modal} className={styles.viewer} onCancel={()=>setPreview(null)} onKeyDown={event=>{if(event.key==="ArrowLeft"||event.key==="ArrowRight"){event.preventDefault();step(event.key==="ArrowLeft"?-1:1);}}}>
      <header><h2>{preview.index+1} / {preview.items.length} · {current.title}</h2><button onClick={()=>setPreview(null)}><X size={20}/> Close</button></header>
      <div><button aria-label="Previous item" disabled={preview.index===0} onClick={()=>step(-1)}><ChevronLeft/></button>{current.youtubeId?/^[\w-]{11}$/.test(videoId(current.youtubeId))?<iframe key={current.id} title={current.title} src={`/guard-admin/cloud-learning-player.html#${new URLSearchParams({video:videoId(current.youtubeId),start:"0"})}`} sandbox="allow-scripts allow-same-origin" allow="autoplay; encrypted-media; fullscreen"/>:<p>Enter a valid YouTube video link first.</p>:image?<img src={image} alt={current.title}/>:<p>{previewError||"Loading preview…"}</p>}<button aria-label="Next item" disabled={preview.index===preview.items.length-1} onClick={()=>step(1)}><ChevronRight/></button></div><footer>← → Browse · Esc Close</footer>
    </dialog>}
  </main>;
}
