export type Item={id:string;category:string;title:string;description:string;youtubeId:string;enabled:boolean};
export type Catalog={revision:number;publishedVersion:number;updatedAt:string;items:Item[];history:{version:number;published_at:string}[]};
export type Overview={ai?:AiUsage;asOf:string;accounts:{total:number;new:number;trials:number;active:number;complimentary:number};devices:{total:number;online:number;active_families:number};onboarding:{started:number;completed:number};downloads:{requests:number;families:number;first_tracked:string|null};daily:{date:string;count:number}[];versions:{version:string;computers:number}[];errors:{component:string;code:string;version:string;count:number;latest:string}[];outcomes:{completed:number;failed:number;errors:number};activity:{families:number;students:number;seconds:string};adoption:{category:string;approved:number;skipped:number}[];audit:{action:string;version:number|null;created_at:string}[]};
export type Report={id:string;receivedAt:string;component:string;code:string;version:string;osVersion:string;stage:string;windowsError:number;errorType:string;location:string};

export type AiUsage={totals:{requests:number;families:number;cost_micros:string;estimated_requests:number;first_tracked:string|null};features:{feature:string;model:string;requests:number;cost_micros:string}[];families:{family:string;billing_mode:string;requests:number;cost_micros:string;included_micros:string;child_computer_limit:number}[]};

export type UsageCounters={requests:number;clientErrors:number;serverErrors:number;aborted:number;requestBytes:number;responseBytes:number;dbQueries:number;dbResultBytes:number;durationMs:number;maxResponseBytes:number;aiRequests:number;aiCostMicros:number;aiEstimatedMicros:number};
export type UsageRow=UsageCounters&{feature?:string;family?:string;label?:string;date?:string};
export type ResourceUsage={asOf:string;from:string;days:number;family:string;firstTracked:string|null;lastRecorded:string|null;truncated:boolean;totals:UsageCounters;features:UsageRow[];families:UsageRow[];daily:UsageRow[];warnings:string[];neon:{status:string;message?:string|null;fetchedAt?:string|null;nextRefreshAt?:string|null;data?:{source:string;projectId:string;from:string;to:string;plan:string|null;dataThrough:string|null;points:number;summary?:{computeSeconds:number;transferBytes:number;storageBytes:number;periodEnd:string|null};totals:Record<string,number>;daily:{date:string;computeSeconds:number;transferBytes:number}[]}|null}};
