"use client";
import {useEffect,useState} from "react";
import {Activity,ArrowDownUp,ArrowLeft,BarChart3,Database,DollarSign,RefreshCw,TriangleAlert,Users} from "lucide-react";
import type {ResourceUsage,UsageRow,UsageCounters} from "./types";
import styles from "./admin.module.css";
const labels:Record<string,string>={"coloring-studio":"Coloring Studio","math-coach":"Math Coach","parent-assistant":"Parent Assistant","learning-videos":"Learning videos","family-watch":"Family Watch","science-spelling":"Science Spelling","sync":"Connection & settings","activation":"Computer activation","other":"Other / unknown","operator":"Staff dashboard","legacy":"LAN imports","daily":"Daily questions"};
const feature=(id:string)=>labels[id]||id.charAt(0).toUpperCase()+id.slice(1).replaceAll("-"," ");
const count=(n:number)=>n.toLocaleString();
const money=(micros:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:micros>0&&micros<10000?4:2}).format(micros/1e6);
const bytes=(n:number)=>{if(n<1024)return `${count(n)} B`;const units=["KiB","MiB","GiB","TiB"];let value=n/1024,i=0;while(value>=1024&&i<units.length-1){value/=1024;i++;}return `${value.toLocaleString(undefined,{maximumFractionDigits:2})} ${units[i]}`;};
const stamp=(n:string|null|undefined)=>n?new Date(n).toLocaleString():"Not yet available";
type Sort="transfer"|"dbResultBytes"|"requests"|"serverErrors"|"aiCostMicros";
const transfer=(row:UsageCounters)=>row.requestBytes+row.responseBytes;
export default function UsagePanel(){
  const [days,setDays]=useState(7),[family,setFamily]=useState(""),[families,setFamilies]=useState<UsageRow[]>([]),[data,setData]=useState<ResourceUsage|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[sort,setSort]=useState<Sort>("dbResultBytes"),[reload,setReload]=useState(0);
  useEffect(()=>{const controller=new AbortController();setBusy(true);setError("");
    void fetch("/guard/admin/bridge/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"usage",days,family}),cache:"no-store",signal:controller.signal})
      .then(async response=>{const result=await response.json();if(!response.ok)throw Error(result.error||"Usage could not be loaded.");return result as ResourceUsage;})
      .then(result=>{if(controller.signal.aborted)return;setData(result);if(!family)setFamilies(result.families);})
      .catch(error=>{if(!controller.signal.aborted)setError(error instanceof Error?error.message:"Usage could not be loaded.");})
      .finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();
  },[days,family,reload]);
  function table(rows:UsageRow[],kind:"feature"|"family"){
    const ordered=[...rows].sort((a,b)=>(sort==="transfer"?transfer(b)-transfer(a):b[sort]-a[sort])||b.requests-a.requests);
    return <div className={styles.usageTable}><table><caption>{kind==="feature"?"Usage by feature":"Usage by family"}</caption><thead><tr><th>{kind==="feature"?"Feature":"Family"}</th><th>Requests</th><th>Server errors</th><th>API transfer</th><th>DB queries</th><th>DB results · est.</th><th>AI spending · est.</th></tr></thead><tbody>{ordered.map(row=><tr key={row.feature||row.family}><th scope="row">{kind==="family"?<button className={styles.familyLink} onClick={()=>setFamily(row.family!)} disabled={busy}>{row.label}</button>:feature(row.feature!)}<small>{kind==="feature"&&row.requests?`Largest response: ${bytes(row.maxResponseBytes)}`:""}</small></th><td>{count(row.requests)}</td><td className={row.serverErrors?styles.hot:undefined}>{count(row.serverErrors)}{row.requests>0&&row.serverErrors>0&&<small>{(row.serverErrors/row.requests*100).toFixed(1)}%</small>}</td><td title={`Uploaded ${bytes(row.requestBytes)} · Downloaded ${bytes(row.responseBytes)}`}>{bytes(transfer(row))}</td><td>{count(row.dbQueries)}</td><td>{bytes(row.dbResultBytes)}</td><td>{money(row.aiCostMicros)}<small>{count(row.aiRequests)} AI calls</small></td></tr>)}</tbody></table>{!rows.length&&<p className={styles.usageEmpty}>No recorded activity in this range.</p>}</div>;
  }
  const neon=data?.neon,db=neon?.data,summary=db?.summary,dbTotals=db?.totals,storageHours=dbTotals?(dbTotals.root_branch_bytes_month+dbTotals.child_branch_bytes_month+dbTotals.instant_restore_bytes_month+dbTotals.snapshot_storage_bytes_month):0;
  const monthHours=db?new Date(Date.UTC(Number(db.from.slice(0,4)),Number(db.from.slice(5,7)),0)).getUTCDate()*24:1;
  return <section aria-busy={busy}>
    <div className={styles.sectionHead}><div><h2>Usage & costs</h2><p>Find expensive features and families. Refresh when you need a new reading.</p></div><button disabled={busy} onClick={()=>setReload(value=>value+1)}><RefreshCw size={16} className={busy?styles.spinning:undefined}/>{busy?"Loading…":"Refresh usage"}</button></div>
    <div className={styles.usageFilters}><label>Range<select value={days} onChange={event=>setDays(Number(event.target.value))} disabled={busy}><option value={1}>Last 24 hours</option><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option></select></label><label><Users size={16}/> Family<select value={family} onChange={event=>setFamily(event.target.value)} disabled={busy}><option value="">All families</option>{families.map(row=><option key={row.family} value={row.family}>{row.label}</option>)}</select></label><label><ArrowDownUp size={16}/> Sort tables by<select value={sort} onChange={event=>setSort(event.target.value as Sort)}><option value="dbResultBytes">Database result bytes</option><option value="transfer">API transferred bytes</option><option value="requests">Requests</option><option value="serverErrors">Server errors</option><option value="aiCostMicros">AI spending</option></select></label>{family&&<button onClick={()=>setFamily("")} disabled={busy}><ArrowLeft size={16}/> All families</button>}</div>
    {error&&<p className={styles.error} role="alert">{error}</p>}
    {data&&<>
      <p className={styles.updated}>App usage: {stamp(data.from)} – {stamp(data.asOf)} · Database readings below show their own reporting period.</p>
      {data.warnings.map(warning=><p className={styles.usageWarning} key={warning}><TriangleAlert size={18}/>{warning}</p>)}
      {data.truncated&&<p className={styles.usageWarning}>This is a partial result. Select one family or a shorter range.</p>}
      {!data.firstTracked&&<p className={styles.notice}>Request and byte tracking starts with this deployment. Earlier traffic cannot be reconstructed. Existing AI records are included.</p>}
      <div className={styles.stats}>{[{label:"API requests",value:count(data.totals.requests),detail:`${count(data.totals.serverErrors)} server errors · ${count(data.totals.clientErrors)} client errors`,Icon:Activity},{label:"API transferred",value:bytes(transfer(data.totals)),detail:`Up ${bytes(data.totals.requestBytes)} · Down ${bytes(data.totals.responseBytes)}`,Icon:ArrowDownUp},{label:"Database results",value:bytes(data.totals.dbResultBytes),detail:`Estimated · ${count(data.totals.dbQueries)} queries`,Icon:Database},{label:"AI spending",value:money(data.totals.aiCostMicros),detail:`${count(data.totals.aiRequests)} calls · includes ${money(data.totals.aiEstimatedMicros)} reserved / estimated`,Icon:DollarSign}].map(({label,value,detail,Icon})=><article key={label}><Icon size={22}/><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div>
      <section className={styles.panel}><h2><BarChart3 size={20}/> API transfer by day</h2><div className={styles.usageChart}>{data.daily.map(day=><div key={day.date} title={`${day.date}: ${bytes(transfer(day))}; ${count(day.requests)} requests`}><span style={{height:Math.max(3,transfer(day)/Math.max(1,...data.daily.map(transfer))*95)}}/><small>{day.date?.slice(5)}</small></div>)}{!data.daily.length&&<p>No traffic recorded yet.</p>}</div></section>
      <section className={styles.panel}><h2><Activity size={20}/> By feature{family?" · selected family":""}</h2>{table(data.features,"feature")}</section>
      {!family&&<section className={styles.panel}><h2><Users size={20}/> By family</h2><p>Choose a family to see which features are responsible.</p>{table(data.families,"family")}</section>}
      <section className={styles.panel}><div className={styles.sectionHead}><h2><Database size={20}/> Neon database</h2><span className={neon?.status==="connected"?styles.usageConnected:styles.usageWarning}>{neon?.status==="connected"?"Connected":neon?.status==="stale"?"Stale reading":neon?.status==="unconfigured"?"Connection needed":neon?.status==="waiting"?"Waiting for metrics":neon?.status==="loading"?"Reading requested":"Unavailable"}</span></div>
        <p>Reported by Neon for the BodeeGuard project, across all families. Cached for one hour.</p>{neon?.message&&<p className={styles.usageWarning}>{neon.message}</p>}
        {db&&db.points>0&&(summary?<>
          <div className={styles.stats}>
            <article><span>Compute</span><strong>{(summary.computeSeconds/3600).toLocaleString(undefined,{maximumFractionDigits:2})}</strong><small>CPU-hours · current billing period</small></article>
            <article><span>Database transfer</span><strong>{bytes(summary.transferBytes)}</strong><small>Neon-reported egress · current billing period</small></article>
            <article><span>Current storage</span><strong>{bytes(summary.storageBytes)}</strong><small>Database and WAL · all project branches</small></article>
          </div>
          <p className={styles.updated}>Period starts {stamp(db.from)}{summary.periodEnd?` · Resets ${stamp(summary.periodEnd)}`:""} · Fetched {stamp(neon?.fetchedAt)} · Next refresh after {stamp(neon?.nextRefreshAt)}</p>
          <p>Current totals from Neon. Detailed billing history is unavailable with this connection. Provider readings can lag; Neon does not supply their measurement time.</p>
        </>:<><div className={styles.stats}><article><span>Compute</span><strong>{(dbTotals!.compute_unit_seconds/3600).toLocaleString(undefined,{maximumFractionDigits:2})}</strong><small>CU-hours</small></article><article><span>Public transfer</span><strong>{bytes(dbTotals!.public_network_transfer_bytes)}</strong><small>Neon-reported database egress</small></article><article><span>Private transfer</span><strong>{bytes(dbTotals!.private_network_transfer_bytes)}</strong><small>Private database network</small></article><article><span>Storage usage</span><strong>{(storageHours/1024**3/monthHours).toLocaleString(undefined,{maximumFractionDigits:3})}</strong><small>GiB-month equivalent · includes restore / snapshots</small></article></div><p className={styles.updated}>{db.plan?`Plan: ${db.plan} · `:""}Data through {stamp(db.dataThrough)} · Fetched {stamp(neon?.fetchedAt)} · Next refresh after {stamp(neon?.nextRefreshAt)}</p></>)}
        <a href="https://console.neon.tech/" target="_blank" rel="noreferrer">Open Neon</a>
      </section>
      <details className={styles.panel}><summary>What these numbers include</summary><p>API transfer counts request and response bodies, before transport compression. It excludes headers, TLS overhead, direct Cloudflare downloads, and YouTube streams. Database-result bytes are an estimate for finding expensive reads; use Neon’s reported transfer for billing totals. AI spending uses the existing model rates and includes uncertain charges held after timeouts.</p><p>Family attribution comes from verified parent or computer credentials. Unauthenticated and system traffic is shown separately. No message text, school passwords, prompts, file contents or browser history are stored in these counters.</p><p>Counters are compact hourly totals, with no background dashboard polling. Failed monitoring writes back off; outages or terminated requests can leave gaps. First retained request data: {stamp(data.firstTracked)}. Last saved: {stamp(data.lastRecorded)}.</p></details>
    </>}
  </section>;
}
