"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {ArrowLeft,Check,ChevronDown,CreditCard,LoaderCircle,Monitor,Plus,Sparkles} from "lucide-react";
import {reviewBodeeGuardPlan,confirmBodeeGuardPlan,buyBodeeGuardAiBoost} from "../actions";
import styles from "./plan.module.css";
export type AiAllowance={includedCredits:number;remainingCredits:number;remainingPercent:number;boostAllowances:number;resetsAt:string;boostPriceCents:number};
type Quote={computers:number;monthlyCents:number;dueNowCents:number;currency:string;creditCents:number;renewalAt:string;token:string};
const money=(cents:number,currency="usd")=>new Intl.NumberFormat("en-US",{style:"currency",currency}).format(cents/100);
export default function PlanControls({limit,connected,canChange,complimentary,allowance}:{limit:number;connected:number;canChange:boolean;complimentary:boolean;allowance:AiAllowance|null}){
  const router=useRouter(),[computers,setComputers]=useState(limit),[quote,setQuote]=useState<Quote|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,start]=useTransition();
  function review(){start(async()=>{setError("");setNotice("");const result=await reviewBodeeGuardPlan(computers);if("error" in result)setError(result.error||"The plan could not be reviewed.");else setQuote(result as Quote);});}
  function confirm(){if(!quote)return;start(async()=>{setError("");const result=await confirmBodeeGuardPlan(quote.token);if("error" in result){setError(result.error);setQuote(null);}else if(result.url)window.location.assign(result.url);else{setQuote(null);setNotice(result.pending?"Payment is pending. Your current plan remains in place.":"Plan updated. Your new computer allowance is ready.");router.refresh();}});}
  return <div className={styles.area}>
    <div className={styles.planLine}><Monitor size={20}/><div><strong>10 computers included · $19.99/month</strong><p>More computers are $2.99 each per month. Parent phones and browsers are included.</p></div></div>
    {canChange?<details className={styles.editor}><summary><Plus size={17}/> Add or change computers <ChevronDown size={16}/></summary>
      {quote?<div className={styles.review}><h3>Review your plan</h3><dl><div><dt>Computer allowance</dt><dd>{quote.computers}</dd></div><div><dt>New monthly price</dt><dd>{money(quote.monthlyCents,quote.currency)} before tax</dd></div><div><dt>Due now</dt><dd>{money(quote.dueNowCents,quote.currency)}</dd></div>{quote.creditCents>0&&<div><dt>Credit toward future invoices</dt><dd>{money(quote.creditCents,quote.currency)}</dd></div>}</dl><p>Stripe calculates the adjustment for the rest of this billing period. Confirming authorizes the payment using your saved payment method.</p><div className={styles.buttons}><button disabled={busy} onClick={()=>setQuote(null)}><ArrowLeft size={16}/> Back</button><button className={styles.primary} disabled={busy} onClick={confirm}>{busy?<LoaderCircle size={16}/>:<Check size={16}/>} Confirm plan change</button></div></div>:
      <form onSubmit={event=>{event.preventDefault();review();}}><label>Total computers<input aria-label="Total computers" type="number" min={Math.max(10,connected)} max={1000} value={computers} onChange={event=>setComputers(Number(event.target.value))} required disabled={busy}/></label><strong>{money(1999+Math.max(0,computers-10)*299)}/month before tax</strong><button disabled={busy||computers===limit} className={styles.primary}>{busy?<LoaderCircle size={16}/>:<CreditCard size={16}/>} Review change</button><p>Review the exact adjustment before confirming. Remove unused computers before reducing your allowance.</p></form>}
    </details>:<p className={styles.note}>{complimentary?"Your complimentary access is unchanged.":"Computer upgrades are available with an active paid subscription. Resume a canceled plan before changing it."}</p>}
    {error&&<p role="alert" className={styles.error}>{error}</p>}{notice&&<p role="status">{notice}</p>}
    {allowance&&<div className={styles.ai}><div><h3><Sparkles size={19}/> Family AI allowance</h3><p>{allowance.includedCredits} credits each month, shared by all children.</p><progress aria-label="Monthly AI allowance remaining" max={100} value={allowance.remainingPercent}/><p><strong>{allowance.remainingPercent}% remaining</strong> · Resets {new Date(allowance.resetsAt).toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"UTC"})}{allowance.boostAllowances>0&&<><br/>{Math.round(allowance.boostAllowances*300)} extra credits remaining</>}</p></div><div><p>AI questions, new drawings and new narration use credits. Usage varies with the request. Saved lessons, pictures and audio remain available.</p>{canChange&&<form action={buyBodeeGuardAiBoost}><button className={styles.primary} disabled={busy}><Plus size={16}/> Add 300 AI credits · $5</button><small>One-time purchase through Stripe. Extra credits carry forward. No automatic charges.</small></form>}</div></div>}
  </div>;
}
